### ISSUE TITLE
What happened when I let my students fork the syllabus

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#10]
Proposed chapter from Heidi Ellis:

> I teach a traditional "get to know college" course for freshmen. It's designed to help new students work on the skills they'll need to be successful in college, such as time management, personal management, and communication. It's also become a prime opportunity for me to introduce freshman students to the guiding principles of open culture. I've developed a method for treating my class as an open organization. To create a more collaborative and inclusive environment, I let the students co-construct the official course syllabus. Here's how I do it—and what students have taught me about the value of making our classrooms more open.

**Comment by afchernik** [comment]
In her case study, Heidi finds a direct connection between student engagement and what she calls an “open approach” to learning. What are some examples Heidi gives that demonstrate this connection? What strategies have you tried that successfully increased student engagement? Do any of these strategies integrate open principles?

Community is an essential principle of an open organization. Heidi talks about how an emphasis on community not only engaged her students in the learning process, but taught her valuable lessons as well. What did Heidi learn about the community norms of her students? How did Heidi and her students resolve differences in these norms?

Heidi reflects that when she invited her students to collaborate in the co-construction of important course documents, like the disruption policy and the policy regarding work submitted late, on GitHub, only a very small number of students forked the documents and made changes. Why do you think more students did not engage in this collaborative process? Do you think the complexity of the technology (in this case GitHub) got in the way? What are some other, low-tech solutions you might use with your own students to catalyze robust collaboration?
