### ISSUE TITLE
Making computer science curricula as adaptable as our code

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#15]
Proposed chapter from Amarachi Achonu:

> Educators in elementary computer science face a lack of adaptable curricula. Calls for more modifiable, non-rigid curricula are therefore enticing—assuming that such curricula could benefit teachers by increasing their ability to mold resources for individual classrooms and, ultimately, produce better teaching experiences and learning outcomes. Our team at CSbyUs noticed this scarcity, and we've created an open source web platform to facilitate more flexible, adaptable, and tested curricula for computer science educators. The mission of the CSbyUs team has always been utilizing open source technology to improve pedagogy in computer science, which includes increasing support for teachers. Therefore, this project primarily seeks to use open source principles—and the benefits inherent in them—to expand the possibilities of modern curriculum-making and support teachers by increasing access to more adaptable curricula.

**Comment by afchernik** [comment]
Amarachi notes that integrating open source practices into curriculum development is key to making that curriculum adaptable for different students. What are some of these practices? What is the relationship between these practices and a moldable curriculum?

Although it is easy to see the advantages of personalizing computer science curricula through what Amarachi calls the “back-and-forth” iterative process of curriculum development, would this kind of process work at your own organization? What are some roadblocks that educators at your organization might face if they try this kind of process?

Amarachi explains that working with an adaptable computer science curriculum is especially important when teaching students who are traditionally underrepresented in the field of computer science. What do you think is the connection between a curriculum’s adaptability and the level of engagement from such students? What are some examples of times you have experienced, either as an educator or a student, a disconnect between a curriculum and a student population?
