### ISSUE TITLE
Dutch Case Study

### ISSUE THREAD

**Issue by ghost** [open-organization-ambassadors/open-org-educators-guide#2]
After reading the README and table of contents I immediately was thinking about a Dutch foundation This foundation is supporting Dutch education with IT topics. They have a platform c which supports teachers to freely create online lessons, which will be openly shared with others. It's kinda a search engine for free lessons with a functionality to create lessons by yourself and share them. The whole wiki integrates with Moodle (the open source learning platform) so as far as I know you can import open lessons in a Moodle platform.

Also, they link to an other foundationn hich is a foundation which supports "open learning material" and they are hosting the "Star collections" which are completely open digital learning lines for secondary education, which are created by a group of teachers and developers. I am not sure if open in these means free, but it seems like a example of learning material which are produced transparent, with collaboration in a teacher community.

If this sounds interesting I can see if I can contact them if they want to share some knowledge and information.

Also I will send the Github URL to someone I know which is in educational development and is also highly involved with digital learning platforms and programs, maybe she has more knowledge to share about this topic (from a West-European perspective).

Last but not least, maybe it is worth to create a issue (together with @jimmysjolund ?) to think about any idea's on students' perspectives in Europe.

**Comment by semioticrobotic** [comment]
I think this is a wonderful idea and I'm very glad you made this connection to the book, @sourceopenNL. Please do feel free to pass this invitation along to your networks.

I agree that the book desperately lacks international perspectives on open educational organizations and I'd welcome any and all proposals to rectify that!

**Comment by semioticrobotic** [comment]
Just checking on this, @sourceopenNL. Do you still plan on submitting something on these topics to the book?

**Comment by ghost** [comment]
@semioticrobotic Hi Bryan, still in planning but didn't have too much time left to contact the foundation. I just sent them an e-mail, hopefully to get a response next week (it's bank holiday this Monday). If they are enthusiastic and acknowledge to share more details and knowledge about their project, I can translate it to a concept case study and submit it.

**Comment by semioticrobotic** [comment]
Got it. Thanks very much for this update, @sourceopenNL. Final chapters will be [due July 12](https://github.com/open-organization-ambassadors/open-org-educators-guide#project-timeline), so as long as we can get it wrapped up by then, we'll be in good shape.

**Comment by ghost** [comment]
Will close this issue, was unable to actively involve the right people in this. But I think there are user stories enough to make it to final.
