### ISSUE TITLE
The future of ethical tech education must be open

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#22]
Proposed chapter from Justin Sherman

**Comment by afchernik** [comment]
Justin does not make a specific call to computer science or other technology educators, but rather argues that all “open-minded teachers” have a responsibility to educate students about “the power and pervasiveness of algorithmic activity.” Why do you think Justin does not limit his call to technology subject matter experts? Do you see relevance between issues of algorithmic justice and the subject matter you teach?

One of the most serious problems facing technology education and design, according to Justin, is lack of inclusivity. How might increasing inclusivity improve artificial intelligence and algorithms? How can a focus on inclusivity push back against what Justin calls “mainstream narratives about technology”?

According to Justin, why is the open value of adaptability so essential in the context of ethical technology education? What role might students play in “feedback loops” pertaining to ethical technology education? What are some examples of relevant organizations in your local community with whom students might collaborate on feedback loops?

**Comment by trncb** [comment]
Just a couple of copyedit suggestions:

**Solutions through open ethical tech education**

*1st paragraph:*
From "... fostering an ethics that addresses the potentially ..."
To "... fostering ethics that address the potentially ..."

*6th paragraph:*
From "... other algorithms in particular are often ..."
To "... other algorithms, in particular, are often ..."
