### ISSUE TITLE
Afterword

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#27]
Book afterword from Ben Owens:

> Open organization principles—transparency, inclusivity, adaptability, collaboration, and community—have the potential to completely change this educational paradigm, to make it more relevant to the needs of today's students and their communities, and to help them better develop the skills, knowledge, and dispositions they'll need to thrive in the midst of a 4th Industrial Revolution. Just as the open source movement has catalyzed the digital revolution and innovation economy, an approach to education borne of the open source movement has the potential to enable any education stakeholder to capture the true promise of a more equitable education system for all students.

**Comment by engineerteacher** [comment]
Proposed Introduction (instead of the Agile article, which could be moved, if appropriate). Thoughts?

We live in unprecedented times, where the only thing that is certain: change. Change the likes of which the world has never seen, where people have more access to information than at any time in human history and disruptive technologies change our lives on an almost daily basis. The acquisition of knowledge is no longer limited to traditional institutions and anyone with a smartphone is now more networked and has more access to information than all their ancestors combined. 

So why is it that our education systems have remained essentially frozen in time for over 100 years? Why do too many students see "doing school" as a passive exercise, irrelevant to their interests and ambitions? Why do too many educators who come into the profession to make a difference for all students become disillusioned with the institutional inertia of the status quo? And why do too many students either drop out of traditional educational programs or finish their formal educational career with lots of debt and still no clear idea of what they want to do in life? 

One of the catalyzing factors that has enabled society’s phenetic pace of change is the open source movement. With its emphasis on rapid, crowdsourced prototyping, the open source approach to software development has in only 20 years, moved from the fringes to become a primary driver in today’s innovation economy. This reality points to the need for every education stakeholder to make a critical decision: either  embrace these changes or face the reality of irrelevance. 

Forward-thinking people and organizations across the globe are responding to these challenges through collective action to harness open source technologies and societal expectations for openness and transparency. Our legacy systems of government, corporations, and even organizations such as the military are becoming more responsive to the needs of the marketplace and the communities they serve and it’s at this crossroads that educators find themselves. Are we willing to make the same kind of dynamic shift or will we continue to assume that the same industrial model of education we have relied on for far too long is somehow good enough for our modern world?

The principles of open organizations such as transparency, inclusivity, adaptability, collaboration, and community have the potential to completely change this educational paradigm to make it more relevant to the needs of today’s students—helping them better develop the skills, knowledge, and dispositions to thrive in the midst of a 4th Industrial Revolution. It is an approach borne out of the open source movement that has catalyzed the digital revolution and innovation economy and has the potential to enable any education stakeholder to capture the true promise of a more equitable education system for all students.

The Open Organization Guide for Educators offers stories from open education experts from around the world, including students, K‒12 teachers, university faculty, CIOs, and leaders of educational non-profits. It offers a timely response to the questions posed above. It provides readers with case studies and best practices that have been proven to work in a myriad of educational contexts - each with the potential to be adapted and remixed to meet the needs of one’s local learning community. 

It is a volume that points to the cultural changes needed for any school to leverage its collective talents and expertise in a more open manner so that is a stark antidote to a closed legacy model of school that is simply not working for many of our students - especially students furthest from opportunity.

**Comment by afchernik** [comment]
Love this, Ben. I wrote something quite similar (no surprise there!) that Bryan is currently reviewing. Bryan, do you see similarities?

**Comment by engineerteacher** [comment]
Fantastic! Bryan: Please feel free to merge what I wrote with what Aria did. Thanks!

**Comment by semioticrobotic** [comment]
Great work, @engineerteacher. What do you think of the edited version below?

## Proposed introduction

We live in unprecedented times. The only certainty is change the likes of which the world has never seen, where people have greater access to information than they have at any time in history, and where disruptive technologies change our lives on an almost daily basis. Acquiring knowledge is no longer something people do exclusively in traditional, established institutions, and anyone with a smartphone is now more networked and has more access to information than all their ancestors combined.

So why have our education systems remained essentially frozen in time for more than 100 years?

Why do too many students see "doing school" as a passive exercise, irrelevant to their interests and ambitions? Why do too many educators, who enter the profession to make a difference in students lives, become disillusioned with the institutional inertia of the status quo? And why do too many students either drop out of traditional educational programs or finish their formal educational career with lots of debt and _still_ no clear idea of what they want to do in life?

One catalyst of today's frenetic pace of change might also begin to unlock some answers to questions like those: the open source movement.

With its emphasis on rapid, crowdsourced prototyping, the open source approach to software development has in only 20 years shifted from fringe technical communities to become a primary driver of today's innovation economy. Forward-thinking people and organizations across the globe are responding to challenges through collective action to harness both open source technologies and societal expectations for greater openness and transparency. Legacy models of government, the corporation, and even the military are becoming more responsive to these changes. Now every education stakeholder to make the same, critical decision: embrace these changes or face the reality of irrelevance.

It's at this crossroads that educators find themselves. Are we willing to make the same kind of dynamic shift, or will we continue to assume that the same industrial model of education we have relied on for far too long is somehow good enough for our modern world?

Open organization principles—transparency, inclusivity, adaptability, collaboration, and community—have the potential to completely change this educational paradigm, to make it more relevant to the needs of today's students and their communities, and to help them better develop the skills, knowledge, and dispositions they'll need to thrive in the midst of a 4th Industrial Revolution.

Just as the open source movement has catalyzed the digital revolution and innovation economy, an approach to education _borne_ of the open source movement has the potential to enable any education stakeholder to capture the true promise of a more equitable education system for all students.

_The Open Organization Guide for Educators_ offers stories from open education experts around the world, including students, K‒12 teachers, university faculty, CIOs, and leaders of educational non-profits. It offers a timely response to the questions above, and it provides readers with case studies and best practices that have been proven to work in myriad educational contexts—each with the potential to be adapted and remixed to meet the needs of one's local learning community.

It is a volume that guides readers through the cultural changes any school must enact in order to leverage its collective talents and expertise in a more open manner—a stark antidote to a closed, legacy model of school that is simply not working for many of our students, especially those furthest from opportunity.

**Comment by engineerteacher** [comment]
Looks great! I assume this will replace the "Agile" article altogether...or does it just move into the body of the book. I'm cool with either - even if that's a 2nd edition move. Thanks!

**Comment by semioticrobotic** [comment]
What I'm proposing here would be:

- To make this the new introduction to the book
- To make Aria's great #4 the preface of the book
- To make your previous #35 its own, independent "Visions" chapter

**Comment by engineerteacher** [comment]
Perfect!

**Comment by afchernik** [comment]
@semioticrobotic What do you see as the main differences between my piece (perhaps new preface) and @engineerteacher's? How do you see the difference between the preface and the intro? Am I off thinking the two pieces are so similar?

**Comment by semioticrobotic** [comment]
A great question, @afchernik. In previous installments, prefaces have always been brief "setups" that establish a tone and explain a bit about the book-as-artifact (why it exists, how it came together, etc.). I've always written it. Introductions have always been longer, perhaps from a noted guest writer or outside expert, and more contextual—they provide deeper background on trends, comment on the themes that emerge from the chapters and try to weave some previews of the material (and because they've been more substantial, have always gotten a special "callout" on a title page: "With an introduction by ...").

In our case here, the style of the introduction and the preface are converging somewhat. That's not concerning or "bad" in my opinion—in fact I rather like the tone each of you has struck. But I do agree with your assessment that they're more similar than different. Perhaps we rethink the structure altogether—just begin with "statements from the editors," or a combined introduction, or something else. I'm open to ideas.

**Comment by engineerteacher** [comment]
See what you think...could still use some fine tuning: 

We live in unprecedented times. The only certainty is change the likes of which the world has never seen, where people have greater access to information than they have at any time in history, and where disruptive technologies change our lives on an almost daily basis. Acquiring knowledge is no longer something people do exclusively in traditional, established institutions, and anyone with a smartphone is now more networked and has more access to information than all their ancestors combined.
So why have our education systems remained essentially frozen in time for more than 100 years?
Why do too many students see "doing school" as a passive exercise, irrelevant to their interests and ambitions? Why do too many educators, who enter the profession to make a difference in students lives, become disillusioned with the institutional inertia of the status quo? And why do too many students either drop out of traditional educational programs or finish their formal educational career with lots of debt and still no clear idea of what they want to do in life?
The fact that you are reading this afterward means that you have likely seen how the open source movement can provide powerful answers to these hard questions. The articles in this book provide insight, inspiration, and proven steps that any education stakeholder can take to transform our education systems to better meet the needs of all students. 
With its emphasis on rapid, crowdsourced prototyping, the open source approach to software development has in only 20 years shifted from fringe technical communities to become a primary driver of today's innovation economy. Forward-thinking people and organizations across the globe are responding to challenges through collective action to harness both open source technologies and societal expectations for greater openness and transparency. Legacy models of government, the corporation, and even the military are becoming more responsive to these changes. Educators have to make the same, critical decision: embrace these changes or face the reality of irrelevance.
Are we willing to make the same kind of dynamic shift, or will we continue to assume that the same industrial model of education we have relied on for far too long is somehow good enough for our modern world? The good news is that pioneering educators are embracing a different way, as articulated in this volume. These examples show how the open organization principles —transparency, inclusivity, adaptability, collaboration, and community—have the potential to completely change this educational paradigm, to make it more relevant to the needs of today's students and their communities, and to help them better develop the skills, knowledge, and dispositions they'll need to thrive in the midst of a 4th Industrial Revolution.
The stories you have read in The Open Organization Guide for Educators offer a call to action from open education experts around the world. These case studies and best practices have been proven to work in myriad educational contexts—it’s now time for you to take the bold steps that are needed by adapting and remixing these ideas to meet the challenges of your own learning community.
Just as the open source movement has catalyzed the digital revolution and innovation economy, an approach to education borne of the open source movement has the potential to enable any education stakeholder to capture the true promise of a more equitable education system for all students.
 
The articles in this book have given you the tools to help enable that transformation by leveraging the collective talent and expertise in every school in a more open manner—a stark antidote to a closed, legacy model of school that is simply not working for many of our students, especially those furthest from opportunity. Let’s get started.

**Comment by semioticrobotic** [comment]
Well done, @engineerteacher! I tweaked only a few small areas in the revision proposed here.

## Afterword

We live in unprecedented times. The only certainty is change the likes of which the world has never seen, where people have greater access to information than they have at any time in history, and where disruptive technologies change our lives on a near-daily basis. Acquiring knowledge is no longer something people do exclusively in traditional, established institutions, and anyone with a smartphone is now more networked and has more access to information than all their ancestors combined.

So why have our education systems remained essentially frozen in time for more than 100 years?

Why do too many students see "doing school" as a passive exercise, irrelevant to their interests and ambitions? Why do too many educators, who enter the profession to make a difference in students' lives, become disillusioned with the institutional inertia of the status quo? And why do too many students either drop out of traditional educational programs or finish their formal educational career with lots of debt and still no clear idea of what they want to do in life?

If you're reading this afterword, then you've likely seen how values and principles derived from the open source movement can provide powerful answers to these hard questions. The chapters in this book provide insight, inspiration, and proven steps that any stakeholder in an educational organization can take to transform those institutions and better meet the needs of all students.

With its emphasis on rapid, crowdsourced prototyping, the open source approach to software development has in only 20 years shifted from fringe technical communities to become a primary driver of today's innovation economy. Forward-thinking people and organizations across the globe are responding to challenges through collective action to harness both open source technologies and societal expectations for greater openness and transparency. Legacy models of government, the corporation, and even the military are becoming more responsive to these changes. Educators have to make the same, critical decision: embrace these changes or face the reality of irrelevance.

Are we willing to make this dynamic shift, or will we continue to assume that the same industrial model of education on which we've relied for far too long is somehow good enough for our modern world?

The good news is that pioneering educators are embracing a different way, as articulated in this volume. These examples show how the open organization principles—transparency, inclusivity, adaptability, collaboration, and community—have the potential to completely change this educational paradigm, to make it more relevant to the needs of today's students and their communities, and to help them better develop the skills, knowledge, and dispositions they'll need to thrive in the midst of a 4th Industrial Revolution.

The stories you've read in _The Open Organization Guide for Educators_ are a call to action from open education experts around the world. Their best practices can work in myriad educational contexts; it's now time for _you_ to take the necessary, bold steps by adapting and remixing these ideas to meet the challenges of your own learning community.

Just as the open source movement has catalyzed the digital revolution and innovation economy, an approach to education borne of the open source movement has the potential to enable any education stakeholder to capture the true promise of a more equitable education system for all students. The articles in this book have given you the tools to enable that transformation by leveraging the collective talent and expertise in every school in a more open manner—a stark antidote to a closed, legacy model of school that is simply not working for many of our students, especially those furthest from opportunity.

Let's get started.

**Comment by semioticrobotic** [comment]
I know @engineerteacher is traveling this week, so I will go ahead and typeset this piece now, with the intent to make final corrections (if any) in the galleys.
