### ISSUE TITLE
Rethinking assessment in an open, peeragogical learning environment

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#31]
Proposed chapter from @dpreston14:

> Over the past several decades, digital technologies have driven massive shifts in the way we communicate and collaborate. Information technology, socioeconomic trends, an increasingly complex and uncertain future, and school's failed brand are all part of an emerging discourse that seeks to align contemporary learning practices with our rapidly changing culture. Assessment (and its purposeful use) is an important point of connection between learning communities and other social structures. The processes of giving, receiving, and applying constructive critique makes learners better thinkers, innovators, motivators, collaborators, coworkers, friends, relatives, spouses, teammates, and neighbors. More often than not, the feedback learners receive in their everyday lives comes from peers, not simply authority figures. Helping students become better at both delivering and acting on feedback from peers is essential to their success beyond the classroom today. But implementing peer-based assessment can be problematic in schooling institutions where evaluative authority is traditionally conflated with hierarchical authority, and where economic and political influences have focused attention on summative, quantitative, standardized measurement of learning and intelligence. This chapter will explain two emerging theoretical frameworks designed to leverage end-to-end user principles of communication technology to facilitate peers learning together and teaching each other: Open Source Learning and Peeragogy. These frameworks draw on open principles to decentralize and enrich the assessment process.

**Comment by engineerteacher** [comment]
Possible questions...

1. How does the learning organization you work the closest with bridge the gap between the traditional teacher-centred instruction and assessment model to one that is more collaborative, open, and takes advantage of a peer-based? 
2. What steps can you take to encourage the learning organization you work the closest with to move from an archaic model suited for the industrial age to a "pull based" model, where students have, as the author describes, "high standards without standardization" and thus are better able to develop the skills needed in today's innovation economy?
3. The author offers a compelling case for how Open Source Learning can produce a paradigm shift for teachers and students. How can you and your colleagues leverage the principles of openness to build the trust and transparency needed to affect this change in more classrooms and schools?
