### ISSUE TITLE
The book needs a subtitle

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#34]
_The Open Organization Guide for Educators_ lacks an explanatory and compelling subtitle! Let's give it one.

Book editors will make a final decision, but we're seeking input from all authors, proofreaders, and other community members. We'll keep a running list below.

Why not submit your own? (See previous installments of [the _Open Organization_ book series](https://opensource.com/open-organization/resources/book-series) for inspiration.)

### Subtitle suggestions

- Transforming teaching and learning for the 21st century
- Lesson plans for an open approach to teaching and learning
- Revolutionizing education for a more open future
- Transforming teaching and learning for a more collaborative future
- Revolutionizing teaching and learning for a more collaborative future
- Letting learners in on the secret
- Making learning an invitation

**Comment by stevenov** [comment]
* Letting learners in on the secret
* Making learning an invitation

**Comment by engineerteacher** [comment]
My two favs: "Revolutionizing education for a more open future" or "Letting learners in on the secret"

**Comment by semioticrobotic** [comment]
In another thread, @engineerteacher suggests a mashup of options above to form:

- Revolutionizing teaching and learning for a more collaborative future

**Edit:** Should note that this one has my vote!

**Comment by creisinger** [comment]
+1 for Revolutionizing teaching and learning for a more collaborative future.

**Comment by semioticrobotic** [comment]
Okay!

Book editors met this morning to finalize this important detail. I'm very pleased to share that the book's subtitle will be:

**Transformative teaching and learning for a rapidly changing world**

Editor @afchernik made two important points that led to this final iteration:

- "Revolution," while powerful and motivating, has become somewhat trite in the education space (and on the covers of education books!). While we all like the word and its force, the book's intended audience might not find it all that compelling. (Still—who doesn't love a good revolution?)

- "The future," while important, still seems remote, the stuff of _tomorrow_. But this book is an urgent one; it's about what we must do _today_ to help educational organizations thrive in the world we have _right now_. And that's a world marked by instability and rapid change.

We appreciated having all this excellent feedback to guide or work, and we will certainly retain some of these great phrases and sentiments as we continue crafting promotional materials!
