### ISSUE TITLE
Can schools be agile?

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#35]
Proposed chapter from @engineerteacher:

> While I certainly appreciate the argument that education is an animal significantly different from other professions, I also believe that rethinking an organizational and leadership structure is an applicable exercise for any entity wanting to remain responsible (and responsive) to the needs of its stakeholders. Most other professions have taken a hard look at their traditional, closed, hierarchical structures and moved to ones that encourage collective autonomy per shared goals of excellence—organizational elements essential for continuous improvement. It's time our schools and districts do the same by expanding their horizon beyond sources that, while well intended, are developed from a lens of the current paradigm.

**Comment by engineerteacher** [comment]
Possible questions...

1. The author posed this question early in the article: Why aren't more educational organizations working to create cultures of continuous improvement? He offered two possible reasons, but what OTHER reasons would you suggest? How might those reasons be eliminated (or at least their impact reduced) by leveraging the principles of the open source movement?
2. What are the specific ways you can encourage the learning organization you work the closest with to look beyond the education space for ideas that can foster a culture of continuous improvement?
3. The author asserts that unlike many schools, most other professions have moved away from closed, hierarchical structures to ones that encourage collective autonomy per a shared set of goals. What steps can education stakeholders take to move beyond the current school governance paradigm?

**Comment by semioticrobotic** [comment]
Thanks, @engineerteacher! Could you supply a two-sentence bio statement we can include at the end of this chapter?

**Comment by engineerteacher** [comment]
BIO: Ben Owens was an engineer for a multinational corporation for 18 years before becoming a STEM teacher in rural Appalachia, where he received state and national recognition for his innovative approach to teaching and teacher leadership. He co-authored the book, “_Open Up, Education! How Open Way Learning Can Transform Schools_” and now works as an education consultant to help educators create similar cultural conditions for localized innovation in their own schools.

**Comment by semioticrobotic** [comment]
Set! Thanks, @engineerteacher.

**Comment by semioticrobotic** [comment]
(Edits from Gaby Berkman received in another thread)
