### ISSUE TITLE
Typo on page 14

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-educators-guide#39]
Last paragraph, 2nd line, the word divided is spelled wrong.

![20190912_152634](https://user-images.githubusercontent.com/3680343/64814876-59bc2000-d572-11e9-962e-11660706042e.jpg)

**Comment by semioticrobotic** [comment]
Thanks, @jhibbets! This is now fixed in [v1.01](https://github.com/open-organization-ambassadors/open-org-educators-guide/releases/tag/v1.01).
